version: '3'

services:
  webtrc:
    image: docker.io/martyshu/webai-jupyter:latest
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jupyter.entrypoints=http"
      - "traefik.http.routers.jupyter.rule=Host(`jupyter.webduino.io`)"
      - "traefik.http.middlewares.jupyter-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.jupyter.middlewares=jupyter-https-redirect"
      - "traefik.http.routers.jupyter-secure.entrypoints=https"
      - "traefik.http.routers.jupyter-secure.rule=Host(`jupyter.webduino.io`)"
      - "traefik.http.routers.jupyter-secure.tls=true"
      - "traefik.http.routers.jupyter-secure.service=jupyter"
      - "traefik.http.services.jupyter.loadbalancer.server.port=8888"
      - "traefik.docker.network=traefik-public"      
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/home/wa/work:/home/jovyan/—"
networks:
  traefik-public:
    external: true